package gq.jared.pisaygwa.subj

class Subject(val name: String, val units: Double): Contract.Model {

    var grade: Double = 1.00
    val description: String = "$name ($units)"

    override fun decrementGrade() {
        if (grade > 1.0) {
            grade -= if (grade > 3.0) 1.0 else 0.25
        }
    }

    override fun incrementGrade() {
        if (grade < 5.0) {
            grade += if (grade > 2.75) 1.0 else 0.25
        }
    }

    override fun saveGrade() {
        TODO("not implemented")
    }

    override fun equals(other: Any?): Boolean {
        return other is Subject && this.name == other.name && this.units == other.units
    }

    override fun hashCode(): Int {
        // Auto-generated by Android Studio
        var result = name.hashCode()
        result = 31 * result + units.hashCode()
        result = 31 * result + grade.hashCode()
        result = 31 * result + description.hashCode()
        return result
    }

}